mode: debug
address: :443
url: https://127.0.0.1
name: app
max_ping_count: 10
db:
  username: root
  password: 2w3e$R%T
  address: 10.92.119.202:33306
  database: paas_monitor
tls:
  cert: ./conf/server.crt
  key: ./conf/server.key
